const Discord = require('discord.js')

module.exports.run = async (client, message, args) => {
  
  let array = ["It may be stupid, but it's also dumb!",
"What's the matter, is he stupid?",
"You're right, if I was the mom, this would be kind of shocking...",
"Is mayonnaise an instrument?",
"Whoever's the owner of the white Sudan, you left your lights on.",
"I know, let's get naked!",
"TWO ICECREAMS!",
"Do it again, I wasn't looking! ",
"Y'know, WUMBO, he she me, WUMBO...",
"HERE COMES A GIANT FIST!",
"You guys talk funny! SAY MORE WORDS!",
"Well I don't tell you how to live your life! ",
"You mean like a weenie? OKAY! ",
"Methinks it's mutton-tastic!",
"Sandy's a girl?",
"Hey, we are not chicken! OH NO, MY POPCORN!",
"My pickle started off life in a jar, and now it's in a jar again! It's like, a pun or something!",
" Is he the badguy?",
" NO! THIS IS PATRICK!!!!! I am not a Krusty Krab!",
"Kraaaaaabs.... isn't that the red sweaty guy you work for",
"I don't think this is the real Spongebob. Just look how yellow he is.",
"Me too! INFLATABLE PANTS! WHAT'S YOUR IDEA?",
"I'm mad. I can't see my forehead.",
"Knowledge can never replace friendship. I prefer to be an idiot!",
"Nice try Squidward. But there's no Santa Clause here!",
" OKAY, MAGICAL TALKING TRASHCAN!",
" I gotta get back to crusting the crab.",
"LEEDLE LEEDLE LEEDLE LEE.",
" That's Mr. Dr. Professor Patrick to you!",
"It may be stupid, but it's also dumb!",
"What's the matter, is he stupid?",
"You're right, if I was the mom, this would be kind of shocking...",
"Is mayonnaise an instrument?",
"Whoever's the owner of the white Sudan, you left your lights on.",
"I know, let's get naked!",
"TWO ICECREAMS!",
"Do it again, I wasn't looking! ",
"Y'know, WUMBO, he she me, WUMBO...",
"HERE COMES A GIANT FIST!",
"You guys talk funny! SAY MORE WORDS!",
"Well I don't tell you how to live your life! ",
"You mean like a weenie? OKAY! ",
"Methinks it's mutton-tastic!",
"Sandy's a girl?",
"Hey, we are not chicken! OH NO, MY POPCORN!",
"My pickle started off life in a jar, and now it's in a jar again! It's like, a pun or something!",
" Is he the badguy?",
" NO! THIS IS PATRICK!!!!! I am not a Krusty Krab!",
"Kraaaaaabs.... isn't that the red sweaty guy you work for",
"HAHAHAHA, IT'S A GIRAFFE!",
"RECTANGLES!!!",
"Flatter the customer! Make him feel good! Opens the door. I LOVE YOU",
"We should take Bikini Bottom, and push it somewhere else!",
"BIGGER BOOT!!",
"Kicking! I wanna do some kicking!",
"I don't think this is the real Spongebob. Just look how yellow he is.",
"Me too! INFLATABLE PANTS! WHAT'S YOUR IDEA?",
"I'm mad. I can't see my forehead.",
"Knowledge can never replace friendship. I prefer to be an idiot!",
"Nice try Squidward. But there's no Santa Clause here!",
" OKAY, MAGICAL TALKING TRASHCAN!",
" I gotta get back to crusting the crab.",
"LEEDLE LEEDLE LEEDLE LEE."]
  
  let quote = array[Math.floor((Math.random() * array.length) + 0)]
  
  message.channel.send(quote)
}
module.exports.help = {
  name: "patrick-quote"
}